name: 'Create Github Release'
description: 'Create Github release for a repository'
author: 'Jose Rodriguez'
inputs:
  token:
    description: 'The GitHub token for authentication'
    required: false
  owner:
    description: 'The owner of the repository'
    required: false
  repo:
    description: 'The repository name'
    required: false
  name:
    description: 'The name of the release'
    required: false
  tag:
    description: 'The tag name for the release'
    required: false
  body:
    description: 'The body of the release'
    required: false
  draft:
    description: 'Whether the release should be a draft'
    required: false
    default: false
  prerelease:
    description: 'Whether the release should be a pre-release'
    required: false
    default: false
outputs:
  id:
    description: 'The ID of the created release'
  html_url:
    description: 'URL of the created release in the GitHub repository'
  upload_url:
    description: 'URL for uploading assets to the created release'    
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
branding:
  icon: 'play-circle'
  color: 'blue'  